mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path

# Include Img Post
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # index
    path('', include('ursitey.urls')),
    #
    path('ursitey/', include('ursitey.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/ursitey/urls.py
from django.urls import path




app_name = 'ursitey'
# Aquire views.py
try:
    from .import views
except:
    print('Unable to import views. Please check ursitey/urls.py for more information.' + '\n'
          +'Thank You')

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    # e.g URL: /polls/#/results/
    # -> Result for question #
    path('<int:post_id>/results/', views.results, name='results'),
    # e.g URL: /polls/#/vote/
    # -> You've voted for question #
    path('<int:post_id>/about/', views.vote, name='about'),
]

mysite/ursitey/models.py
from django.db import models
from django.forms import TextInput, Textarea
# import timezone
from django.utils import timezone
# import datetime
import datetime




class Post(models.Model):
    post_title = models.CharField(max_length=125)
    post_content = models.TextField(max_length=2500)
    post_image = models.ImageField(blank=False)

    def __str__(self):
        return self.post_title
        return self.post_content

    published_date = models.DateTimeField('Date Published')

    def published_recently(self):
        return self.published_date >= timezone.now() - datetime.timedelta(days=1)




class Choice(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    choice_text = models.CharField(max_length=450)

    def __str__(self):
        return self.choice_text

    # ↓Field ↓Model
    votes = models.IntegerField(default=0)

mysite/ursitey/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse, Http404
from django.template import loader


from .models import Post

# Index Hello Mini test
def index(request):
    latest_post_list = Post.objects.order_by('-published_date')[:5]
    context = {'latest_post_list': latest_post_list}
    return render(request, 'ursitey/index.html', context)


# Detail 404 Error
def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'ursitey/detail.html', {'post': post})


# Result
def results(request, post_id):
    response = 'Result for post %s.'
    return HttpResponse(response % post_id)


# Voted
def vote(request, post_id):
    return HttpResponse('You\'ve voted for post %s.' % post_id)

mysite/ursitey/templates/ursitey/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Details</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link  rel="stylesheet" type="text/css" href="{% static 'ursitey/css/style0.css' %}" >
    <link  rel="stylesheet" type="text/css" href="{% static 'ursitey/css/post-info.css' %}" >
    <link  rel="stylesheet" type="text/css" href="{% static 'ursitey/css/footer.css' %}" >
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Sitey</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li class="active"><a href="/">About</a></li>
      <li class="active"><a href="/">Contact</a></li>
      <li class="active"><a href="../../admin">Admin</a></li>
    </ul>
  </div>
</nav>

</body>
</html>

mysite/ursitey/templates/ursitey/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Details</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link  rel="stylesheet" type="text/css" href="{% static 'ursitey/css/style0.css' %}" >
    <link  rel="stylesheet" type="text/css" href="{% static 'ursitey/css/post-info.css' %}" >
    <link  rel="stylesheet" type="text/css" href="{% static 'ursitey/css/footer.css' %}" >
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Sitey</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li class="active"><a href="/">About</a></li>
      <li class="active"><a href="/">Contact</a></li>
      <li class="active"><a href="../../admin">Admin</a></li>
    </ul>
  </div>
</nav>
<!-- Post Title -->
<h1>{{ post.post_title }}</h1>
<!-- Post Image -->

<img class='image-content' src="{{ post.post_image}}" alt="{{ post.post_title }}-thumbnail" />

<!-- Post Content -->
<p class="content-info">
    {{ post.post_content }}
</p>

<!-- Back to Index Page -->
<button class="backbtn"><a href="/" >Back</a></button>

<br>
<br>

<!--Footer -->
<footer>
  <p class="footerauthor">Company Name</p>
  <p>Contact information: <a href="mailto:email@example.com">
  email@example.com</a></p>
</footer>+



</body>
</html>

mysite/ursitey/templates/ursitey/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Polls</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'ursitey/css/style0.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'ursitey/css/footer.css' %}" >

</head>


<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Poll Site</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li class="active"><a href="admin/">Admin</a></li>
    </ul>
  </div>
</nav>

<h1>Posts</h1>
<hr/>
<!-- Acquire DB info for posts Start -->
<style>
    .hide{
  display:none;
}
</style>

{% if latest_post_list %}
    <ul>
    {% for post in latest_post_list %}
        <img src="{{ post.post_image}}" alt="{{ post.post_title }}-thumbnail" >
        <li><a href="{% url 'ursitey:detail' post.id %}"><b class="post-title">{{ post.post_title }}</b></a>

    <!-- Post Content Info -->
        <p class="content-info" >
        {{ post.post_content }}
         </p>



        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}

<!-- Acquire DB info for posts End -->
</body>


<!--Footer -->
<footer>
  <p class="footerauthor">Company Name</p>
  <p>Contact information: <a href="mailto:email@example.com">
  email@example.com</a></p>
</footer>+


</html>

mysite/ursitey/templates/ursitey/results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Results</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link  rel="stylesheet" type="text/css" href="{% static 'polls/css/style0.css' %}" >
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Poll Site</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li class="active"><a href="../../admin">Admin</a></li>
    </ul>
  </div>
</nav>
<h1>{{ post.post_title }}</h1>

<div class="results">
{% for choice in post.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</div>

<h4 class="votetext"> Vote Again?</h4>
<div class="voteoption">
<a href="{% url 'ursitey:detail' post.id %}"><button class="button">Yes</button></a>
<a href="{% url 'ursitey:detail' %}"><button class="button">No</button></a>
</div>
</body>
</html>